### PR TITLE
change

### PR DESCRIPTION
**Pull request by calmh**
just a small change

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
@calmh: Merge failed:

```
Nothing to merge, as far as I can tell.
```

**Comment by calmh** [comment]
@st-review merge it

**Comment by st-review** [comment]
:ok_hand: Merged as 7e8924992e4b1ad637f998a0573c339eb040615d. Thanks, @calmh!

**Pull request closed without merging**
