### PR TITLE
Bar

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
OK, merged as 5aaf40221931650b2842a7e7b0372b95d1665222. Thanks, @calmh!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
OK, merged as cda8b547599e76010500a54c8955f8b47c2fcd29. Thanks, @calmh!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Current build status is `failure` -- cowardly refusing to merge.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Current build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
Current build status is `failure` -- cowardly refusing to merge.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Current build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
OK, merged as 1dd52c07a01542e884325fd8fd3388382d0d8c96. Thanks, @calmh!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Current build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:no_good: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:clock1: Build status is `pending`. I'll wait to see if this becomes successful and then merge!

**Comment by st-review** [comment]
:watch: Patiently waited 30m0s for the build status to turn green, but enough is enough. Let me know when things look good.

**Comment by calmh** [comment]
@st-review don't merge this then

**Comment by st-review** [comment]
:no_entry: Preventing merge for the time being. Push a new revision to reset!

**Comment by calmh** [comment]
@st-review stop

**Comment by st-review** [comment]
:no_entry: Preventing merge for the time being. Push a new revision to reset!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Build status is `failure` -- refusing to merge.

**Comment by calmh** [comment]
@st-review merge

Skip-Check: st-review

**Comment by st-review** [comment]
:ok_hand: Merged as 3b4b3464752174924b5a91068264786f37c358e9. Thanks, @calmh!

**Pull request closed without merging**
