### PR TITLE
Test4

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge this please

This is a combination of two commits

This should get reflowed
into a 76 character wide
paragraph. There are both short and long lines in the original of this paragraph. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Comment by st-review** [comment]
OK, merged as cbfb596e1c190d0191e4035a622cd8af89200f64.

**Comment by calmh** [comment]
@st-review merge this please

This is a combination of two commits

This should get reflowed
into a 76 character wide
paragraph. There are both short and long lines in the original of this paragraph. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

**Comment by st-review** [comment]
OK, merged as 61b42387f688bf7e1134a23935d9067a835b38b0.

**Pull request closed without merging**
