### PR TITLE
wip

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Merge failed:

```
Commit subject does not match regexp ^[a-zA-Z0-9_./-]+:\s
```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Commit subject does not match regexp ^[a-zA-Z0-9_./-]+:\s

**Comment by calmh** [comment]
@st-review merge

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
Commit subject does not match regexp `^[a-zA-Z0-9_./-]+:\s` - does it begin with a tag?

**Comment by calmh** [comment]
@st-review merge

foo: bar!

**Comment by calmh** [comment]
@st-review merge

foo: bar!

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/9/head:pr-9
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 2bf4673 The first commit
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 2bf4673 The first commit
$ git clean -fxd
$ git merge --squash --no-commit pr-9
Updating 2bf4673..267da1d
Fast-forward
Squash commit -- not updating HEAD
 foo | 1 +
 1 file changed, 1 insertion(+)
$ git commit -F -
[master a9cc153] foo: bar!
 1 file changed, 1 insertion(+)
$ git rev-parse HEAD
a9cc15379e2893f81b49d2f5327d3f0a22f89acc
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "st-review" is pending        
To git@github.com:calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:calmh/sandbox.git'

```

**Comment by calmh** [comment]
@st-review merge

foo/bar.baz: quux

**Comment by st-review** [comment]
OK, merged as 3b5f0611dbda52540e1678aa84c315c47989cb8f. Thanks, @calmh!

**Comment by calmh** [comment]
@st-review merge

foo/bar.baz: quux

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/9/head:pr-9
$ git fetch -f origin master:orig/master
From github.com:calmh/sandbox
 + 3b5f061...2bf4673 master     -> origin/master  (forced update)
$ git reset --hard
HEAD is now at 3b5f061 foo/bar.baz: quux
$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git reset --hard orig/master
HEAD is now at 2bf4673 The first commit
$ git clean -fxd
$ git merge --squash --no-commit pr-9
Updating 2bf4673..267da1d
Fast-forward
Squash commit -- not updating HEAD
 foo | 1 +
 1 file changed, 1 insertion(+)
$ git commit -F -
[master 2d02a37] foo/bar.baz: quux
 1 file changed, 1 insertion(+)
$ git rev-parse HEAD
2d02a37d11782dfdd5e0b25671f66a09f260670d
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "st-review" is pending        
To git@github.com:calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:calmh/sandbox.git'

```

**Comment by calmh** [comment]
@st-review merge

foo/bar.baz: quux

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/9/head:pr-9
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at 2d02a37 foo/bar.baz: quux
$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git reset --hard orig/master
HEAD is now at 2bf4673 The first commit
$ git clean -fxd
$ git merge --squash --no-commit pr-9
Updating 2bf4673..267da1d
Fast-forward
Squash commit -- not updating HEAD
 foo | 1 +
 1 file changed, 1 insertion(+)
$ git commit -F -
[master 3708590] foo/bar.baz: quux
 1 file changed, 1 insertion(+)
$ git rev-parse HEAD
3708590fd54a0d949e224ce871b96e158c34ed7a
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "st-review" is pending        
To git@github.com:calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:calmh/sandbox.git'

```

**Comment by st-review** [comment]
OK, merged as ed5b7b61030680b254913045f0d40ada2c0cb182. Thanks, @calmh!

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/9/head:pr-9
$ git fetch -f origin master:orig/master
From github.com:calmh/sandbox
   2bf4673..ed5b7b6  master     -> orig/master
$ git reset --hard
HEAD is now at ed5b7b6 foo/bar.baz: quux
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at ed5b7b6 foo/bar.baz: quux
$ git clean -fxd
$ git merge --squash --no-commit pr-9
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Pull request closed without merging**
