### PR TITLE
Pr

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review merge

**Comment by calmh** [comment]
@st-review merge

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Clone failed:

```
$ git clone git@github.com:calmh/sandbox.git calmh/sandbox
Cloning into 'calmh/sandbox'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Clone failed:

```
$ git clone git@github.com:calmh/sandbox.git calmh/sandbox
Cloning into 'calmh/sandbox'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Clone failed:

```
$ git clone git@github.com:calmh/sandbox.git calmh/sandbox
Cloning into 'calmh/sandbox'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Build status is `pending`. I'll wait until it goes green and then merge!

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/18/head:pr-18
From https://github.com/calmh/sandbox
 * [new ref]         refs/pull/18/head -> pr-18
$ git fetch -f origin master:orig/master
From https://github.com/calmh/sandbox
 * [new branch]      master     -> orig/master
$ git reset --hard
HEAD is now at 172326e lib/foo: bar
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 172326e lib/foo: bar
$ git clean -fxd
$ git merge --squash --no-commit pr-18
Updating 172326e..9fa3ecf
Fast-forward
Squash commit -- not updating HEAD
 hej     | 1 +
 newfile | 2 ++
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git commit -F -
[master ef0ef13] next base
 Author: Jakob Borg <jakob@nym.se>
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git rev-parse HEAD
ef0ef13e8fc873c5930efa9b8d43f96d9aa87d2f
$ git push origin master
Username for 'https://github.com': Password for 'https://github.com': remote: Anonymous access to calmh/sandbox.git denied.
fatal: Authentication failed for 'https://github.com/calmh/sandbox.git/'

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/18/head:pr-18
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at ef0ef13 next base
$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git reset --hard orig/master
HEAD is now at 172326e lib/foo: bar
$ git clean -fxd
$ git merge --squash --no-commit pr-18
Updating 172326e..9fa3ecf
Fast-forward
Squash commit -- not updating HEAD
 hej     | 1 +
 newfile | 2 ++
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git commit -F -
[master b0b85a3] next base
 Author: Jakob Borg <jakob@nym.se>
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git rev-parse HEAD
b0b85a357b219d9aadbf0b25aecdfaf9c9dfbc5b
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "test" is expected.        
To https://github.com/calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/calmh/sandbox.git'

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/18/head:pr-18
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at b0b85a3 next base
$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git reset --hard orig/master
HEAD is now at 172326e lib/foo: bar
$ git clean -fxd
$ git merge --squash --no-commit pr-18
Updating 172326e..9fa3ecf
Fast-forward
Squash commit -- not updating HEAD
 hej     | 1 +
 newfile | 2 ++
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git commit -F -
[master 4052ed9] next base
 Author: Jakob Borg <jakob@nym.se>
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git rev-parse HEAD
4052ed9bca92a5e0d0073c5fe2cf73ec63b7632e
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "test" is expected.        
To https://github.com/calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/calmh/sandbox.git'

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/18/head:pr-18
From https://github.com/calmh/sandbox
 * [new ref]         refs/pull/18/head -> pr-18
$ git fetch -f origin master:orig/master
From https://github.com/calmh/sandbox
 * [new branch]      master     -> orig/master
$ git reset --hard
HEAD is now at 172326e lib/foo: bar
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 172326e lib/foo: bar
$ git clean -fxd
$ git merge --squash --no-commit pr-18
Updating 172326e..9fa3ecf
Fast-forward
Squash commit -- not updating HEAD
 hej     | 1 +
 newfile | 2 ++
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git commit -F -
[master d5b4ed7] next base
 Author: Jakob Borg <jakob@nym.se>
 2 files changed, 3 insertions(+)
 create mode 100644 newfile
$ git rev-parse HEAD
d5b4ed74aa29ae955c0baee11f3c2edd6260ded1
$ git push origin master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "test" is expected.        
To https://github.com/calmh/sandbox.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/calmh/sandbox.git'

```

**Comment by calmh** [comment]
@st-review merge

**Comment by st-review** [comment]
:ok_hand: Merged as 4629db11e3cfa0249931f23d049d43e0dd99fb76. Thanks, @calmh!

**Pull request closed without merging**
