### PR TITLE
hej

### PR DESCRIPTION
**Pull request by calmh**
test pr

### CODE REVIEW

**Comment by calmh** [comment]
@st-review: merge this

**Comment by calmh** [comment]
@st-review: merge this

This is the commit subject

The commit fixes some cool things by introducing a file
named "hej" containing the word "hej".

**Comment by st-review** [comment]
```
$ git fetch -f origin refs/pull/2/head:pr/2
$ git fetch -f origin master:orig/master
$ git reset --hard
HEAD is now at dd8222e This is the commit subject
$ git checkout master
Already on 'master'
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
$ git reset --hard orig/master
HEAD is now at e28bc7c Initial commit
$ git clean -fxd
$ git merge --squash --no-commit pr/2
Updating e28bc7c..91ca8e9
Fast-forward
Squash commit -- not updating HEAD
 hej | 1 +
 1 file changed, 1 insertion(+)
 create mode 100644 hej
$ git commit -F -
[master 63c4237] This is the commit subject
 1 file changed, 1 insertion(+)
 create mode 100644 hej
$ git push origin master
remote: Anonymous access to calmh/sandbox.git denied.
fatal: Authentication failed for 'https://github.com/calmh/sandbox.git/'

```

**Comment by calmh** [comment]
@st-review: merge this

This is the commit subject

The commit fixes some cool things by introducing a file
named "hej" containing the word "hej".

**Comment by st-review** [comment]
Merged as 685c8cf678d9e83007d3427e2ff25022be540b3b.

**Comment by calmh** [comment]
@st-review: merge this

**Comment by st-review** [comment]
Sorry, @calmh, I don't know you well enough to allow that.

**Comment by calmh** [comment]
@st-review: merge this

**Comment by st-review** [comment]
Merge failed:

```
$ git fetch -f origin refs/pull/2/head:pr/2
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
$ git fetch -f origin master:orig/master
From github.com:calmh/sandbox
   e28bc7c..685c8cf  master     -> orig/master
$ git reset --hard
HEAD is now at 685c8cf This is the commit subject
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
$ git reset --hard orig/master
HEAD is now at 685c8cf This is the commit subject
$ git clean -fxd
$ git merge --squash --no-commit pr/2
Automatic merge went well; stopped before committing as requested
Squash commit -- not updating HEAD
$ git commit -F -
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

```

**Pull request closed without merging**
