### PR TITLE
Bar

### PR DESCRIPTION
**Pull request by calmh**

### CODE REVIEW

**Comment by calmh** [comment]
@st-review lgtm

**Comment by calmh-sandbox** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:hand: I'm sorry, @calmh-sandbox. I'm afraid I can't do that.

**Comment by calmh-sandbox** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh-sandbox: Noted! Need another LGTM or explicit merge command.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Merge failed:

```
$ git fetch -f origin refs/pull/16/head:pr-16
$ git fetch -f origin master:orig/master
From github.com:calmh/sandbox
   b405a98..d5e583e  master     -> orig/master
 + 3b4b346...d5e583e master     -> origin/master  (forced update)
$ git reset --hard
HEAD is now at 3b4b346 Skip-Check: st-review
$ git checkout master
Already on 'master'
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commit each, respectively.
  (use "git pull" to merge the remote branch into yours)
$ git reset --hard orig/master
HEAD is now at d5e583e lib/foo: bar
$ git clean -fxd
$ git merge --squash --no-commit pr-16
Auto-merging foo
CONFLICT (content): Merge conflict in foo
Squash commit -- not updating HEAD
Automatic merge failed; fix conflicts and then commit the result.

```

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by st-review** [comment]
@calmh-sandbox: Couldn't retrieve your user information - not merging.

**Comment by calmh** [comment]
@st-review lgtm

**Comment by st-review** [comment]
@calmh: Noted! Need another LGTM or explicit merge command.

**Comment by calmh-sandbox** [comment]
@st-review lgtm

**Comment by st-review** [comment]
:ok_hand: Merged as 172326e6a89a067f9eb367d25ef168624b900147. Thanks, @calmh!

**Comment by calmh** [comment]
foo

**Comment by calmh** [comment]
[Built the docs](https://build.syncthing.net/docs/6/)

**Pull request closed without merging**
